# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Triggers on pushes to the default branch (master)
  push:
    branches: ['master']

  # Allows manual triggers from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Inject environment variables
      - name: Set environment variables
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_DATABASE_URL: ${{ secrets.VITE_FIREBASE_DATABASE_URL }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
          VITE_OCTOKIT_AUTH: ${{ secrets.VITE_OCTOKIT_AUTH }}
        run: echo "Environment variables are set."

      - name: Debug environment variables
        run: |
          echo "VITE_OCTOKIT_AUTH is ${{ secrets.VITE_OCTOKIT_AUTH }}"
          echo "VITE_FIREBASE_API_KEY is ${{ secrets.VITE_FIREBASE_API_KEY }}"

      # Step 5: Build the project
      - name: Build project
        run: npm run build

      # Step 6: Configure GitHub Pages
      - name: Configure Pages
        uses: actions/configure-pages@v4

      # Step 7: Upload build artifact
      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      # Step 8: Deploy to GitHub Pages
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4